# League configuration
LEAGUES = {
    "ELITE": {"id": 59, "name": "Eliteserien", "season": 2026, "slug": "eliteserien"},
    "OBOS": {"id": 203, "name": "OBOS-ligaen", "season": 2026, "slug": "1-divisjon"},
    "Cupen": {"id": 206, "name": "NM Cupen", "season": 2026, "slug": "nm-cupen"},
    "WORLD_CUP": {"id": 77, "name": "World Cup", "season": 2026, "slug": "world-cup"},
}
DEFAULT_LEAGUE = "ELITE"

ADMIN_USER_IDS: set[int] = {275572512069517312}

# Default emojis for teams without custom emojis
DEFAULT_HOME_EMOJI = "🏠"
DEFAULT_AWAY_EMOJI = "✈️"

COUNTRY_FLAGS = {
    "Albania": "🇦🇱",
    "Algeria": "🇩🇿",
    "Argentina": "🇦🇷",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Belgium": "🇧🇪",
    "Bolivia": "🇧🇴",
    "Bosnia and Herzegovina": "🇧🇦",
    "Brazil": "🇧🇷",
    "Bulgaria": "🇧🇬",
    "Cameroon": "🇨🇲",
    "Canada": "🇨🇦",
    "Cape Verde": "🇨🇻",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Colombia": "🇨🇴",
    "Congo DR": "🇨🇩",
    "Costa Rica": "🇨🇷",
    "Croatia": "🇭🇷",
    "Curacao": "🇨🇼",
    "Curaçao": "🇨🇼",
    "Czech Republic": "🇨🇿",
    "Czechia": "🇨🇿",
    "DR Congo": "🇨🇩",
    "Democratic Republic of Congo": "🇨🇩",
    "Denmark": "🇩🇰",
    "Dominican Republic": "🇩🇴",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "El Salvador": "🇸🇻",
    "England": "\U0001F3F4\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Greece": "🇬🇷",
    "Haiti": "🇭🇹",
    "Honduras": "🇭🇳",
    "Hungary": "🇭🇺",
    "Iceland": "🇮🇸",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Italy": "🇮🇹",
    "Ivory Coast": "🇨🇮",
    "Jamaica": "🇯🇲",
    "Japan": "🇯🇵",
    "Jordan": "🇯🇴",
    "Korea Republic": "🇰🇷",
    "Kosovo": "🇽🇰",
    "Mali": "🇲🇱",
    "Mexico": "🇲🇽",
    "Morocco": "🇲🇦",
    "Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Nigeria": "🇳🇬",
    "North Macedonia": "🇲🇰",
    "Northern Ireland": "🇬🇧",
    "Norway": "🇳🇴",
    "Panama": "🇵🇦",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Republic of Ireland": "🇮🇪",
    "Romania": "🇷🇴",
    "Saudi Arabia": "🇸🇦",
    "Scotland": "\U0001F3F4\U000E0067\U000E0062\U000E0073\U000E0063\U000E0074\U000E007F",
    "Senegal": "🇸🇳",
    "Serbia": "🇷🇸",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Spain": "🇪🇸",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Tunisia": "🇹🇳",
    "Turkey": "🇹🇷",
    "Turkiye": "🇹🇷",
    "Türkiye": "🇹🇷",
    "UAE": "🇦🇪",
    "Ukraine": "🇺🇦",
    "United Arab Emirates": "🇦🇪",
    "United States": "🇺🇸",
    "Uruguay": "🇺🇾",
    "USA": "🇺🇸",
    "Uzbekistan": "🇺🇿",
    "Venezuela": "🇻🇪",
    "Wales": "\U0001F3F4\U000E0067\U000E0062\U000E0077\U000E006C\U000E0073\U000E007F",
    "Cote d'Ivoire": "🇨🇮",
    "Côte d'Ivoire": "🇨🇮",
}

COUNTRY_NORWEGIAN_NAMES = {
    "Albania": "Albania",
    "Algeria": "Algerie",
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Austria": "Østerrike",
    "Belgium": "Belgia",
    "Bolivia": "Bolivia",
    "Bosnia and Herzegovina": "Bosnia-Hercegovina",
    "Brazil": "Brasil",
    "Bulgaria": "Bulgaria",
    "Cameroon": "Kamerun",
    "Canada": "Canada",
    "Cape Verde": "Kapp Verde",
    "Chile": "Chile",
    "China": "Kina",
    "Colombia": "Colombia",
    "Congo DR": "DR Kongo",
    "Costa Rica": "Costa Rica",
    "Croatia": "Kroatia",
    "Curacao": "Curaçao",
    "Curaçao": "Curaçao",
    "Czech Republic": "Tsjekkia",
    "Czechia": "Tsjekkia",
    "DR Congo": "DR Kongo",
    "Democratic Republic of Congo": "DR Kongo",
    "Denmark": "Danmark",
    "Dominican Republic": "Den dominikanske republikk",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt",
    "El Salvador": "El Salvador",
    "England": "England",
    "France": "Frankrike",
    "Germany": "Tyskland",
    "Ghana": "Ghana",
    "Greece": "Hellas",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungary": "Ungarn",
    "Iceland": "Island",
    "Iran": "Iran",
    "Iraq": "Irak",
    "Italy": "Italia",
    "Ivory Coast": "Elfenbenskysten",
    "Jamaica": "Jamaica",
    "Japan": "Japan",
    "Jordan": "Jordan",
    "Korea Republic": "Sør-Korea",
    "Kosovo": "Kosovo",
    "Mali": "Mali",
    "Mexico": "Mexico",
    "Morocco": "Marokko",
    "Netherlands": "Nederland",
    "New Zealand": "New Zealand",
    "Nigeria": "Nigeria",
    "North Macedonia": "Nord-Makedonia",
    "Northern Ireland": "Nord-Irland",
    "Norway": "Norge",
    "Panama": "Panama",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Poland": "Polen",
    "Portugal": "Portugal",
    "Qatar": "Qatar",
    "Republic of Ireland": "Irland",
    "Romania": "Romania",
    "Saudi Arabia": "Saudi-Arabia",
    "Scotland": "Skottland",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Slovakia": "Slovakia",
    "Slovenia": "Slovenia",
    "South Africa": "Sør-Afrika",
    "South Korea": "Sør-Korea",
    "Spain": "Spania",
    "Sweden": "Sverige",
    "Switzerland": "Sveits",
    "Tunisia": "Tunisia",
    "Turkey": "Tyrkia",
    "Turkiye": "Tyrkia",
    "Türkiye": "Tyrkia",
    "UAE": "De forente arabiske emirater",
    "Ukraine": "Ukraina",
    "United Arab Emirates": "De forente arabiske emirater",
    "United States": "USA",
    "Uruguay": "Uruguay",
    "USA": "USA",
    "Uzbekistan": "Usbekistan",
    "Venezuela": "Venezuela",
    "Wales": "Wales",
    "Cote d'Ivoire": "Elfenbenskysten",
    "Côte d'Ivoire": "Elfenbenskysten",
}

NON_ROLES = ["Sørveradministrator", "bot-fikler", "Norges Fotballforbund", "Tippekuppongmester"]
MAX_MESSAGE_LENGTH = 2000
MAX_ROLE_VALUE = 100

CHANNEL_ID = 1094933846383923320 #Kanal hvor meldinger skal sendes.
GUILD_ID = 1039825091430719559
ALLOWED_GUILDS = [GUILD_ID]

TEAMS = [
    "Kristiansund",
    "Tromsø", 
    "Brann",
    "Sarpsborg 08",
    "Viking",
    "Bodø/Glimt",
    "Odd",
    "Haugesund",
    "Sandefjord",
    "Rosenborg",
    "Strømsgodset",
    "Hamarkameratene",
    "Lillestrøm",
    "KFUM",
    "Fredrikstad",
    "Molde",
    "Moss",
    "Kongsvinger",
    "Bryne",
    "Raufoss",
    "Ranheim",
    "Jerv",
    "Skeid",
    "Stabæk",
    "Sogndal",
    "Vålerenga",
    "Start",
    "Aalesund",
    "Sandnes Ulf",
    "Åsane",
    "Lyn Fotball",
    "Hei",
]

TEAMS_NORSKE_NAVN = {
    "Kristiansund BK": "Kristiansund",
    "Tromso": "Tromsø",
    "Brann": "Brann",
    "Sarpsborg 08 FF": "Sarpsborg 08",
    "Viking": "Viking",
    "Bodo/Glimt": "Bodø/Glimt", #5/10
    "Odds Ballklubb": "Odd",
    "Haugesund": "Haugesund", #9/9
    "Sandefjord": "Sandefjord", #10/10
    "Rosenborg": "Rosenborg", #9/9
    "Stromsgodset": "Strømsgodset", #11/13
    "Ham-Kam": "Ham-Kam", #6/7
    "Lillestrom": "Lillestrøm",# > 9/11
    "KFUM Oslo": "KFUM", #4/4
    "Fredrikstad": "Fredrikstad", #11/11
    "Molde": "Molde", #5/5
    "Moss": "Moss",
    "Kongsvinger": "Kongsvinger",
    "Bryne": "Bryne",
    "Raufoss": "Raufoss",
    "Ranheim": "Ranheim",
    "jerv": "Jerv",
    "Skeid": "Skeid",
    "Stabaek": "Stabæk",
    "Sogndal": "Sogndal",
    "Valerenga": "Vålerenga",
    "Start": "Start",
    "Aalesund": "Aalesund",
    "Sandnes ULF": "Sandnes Ulf",
    "Asane": "Åsane"
}

TEAMS_EMOJI_ID = [
    "<:Brann:1039844066487185429>",
    "<:Glimt:1039831920978169857>",
    "<:Fredrikstad:1039945582917210162>",
    "<:Kristiansund:1039834384854941726>",
    "<:Lillestroem:1039835160125902908>",
    "<:Odd:1039839692373368872>",
    "<:Tromsoe:1039842401025527868>",
    "<:Rosenborg:1059898578883051561>",
    "<:Hamkam:1039832337032163358>",
    "<:Molde:1039836329502052444>",
    "<:KFUM:1039945755814805574>",
    "<:Stroemsgodset:1039841950079143937>",
    "<:Viking:1039842907894599760>",
    "<:Sandefjord:1039840813544378418>",
    "<:Haugesund:1039832977158443058>",
    "<:Bryne:1039945160374632489>",
    "<:Vaalerenga:1039843306043080735>"
]
